name: 'dbt_raw_to_target'
version: '1.0.0'
config-version: 2

profile: 'dbt_raw_to_target'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dbt_raw_to_target:
    staging:
      +materialized: table
      +schema: stg
    intermediate:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold